// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_attempt1_1_H
#define WINRT_attempt1_1_H
#include "winrt/impl/attempt1.0.h"
WINRT_EXPORT namespace winrt::attempt1
{
    struct __declspec(empty_bases) IBlankPage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IBlankPage>
    {
        IBlankPage(std::nullptr_t = nullptr) noexcept {}
        IBlankPage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
